name: opinions-assemble
proxy:
  appserver:
    - opinions.lndo.site
services:
  appserver:
    type: php:7.2
    webroot: public
    via: apache
    ssl: false
  database:
    type: mariadb
#    portforward: 3310
    creds:
      user: opinions
      password: assemble
      database: oa
#  node:
#    type: node:6.10
#    globals:
#      grunt-cli: "latest"
tooling:
  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - composer
      - --ansi
  php:
    service: appserver
  mysql:
    service: database
    description: Drop into a MySQL shell
    user: root
  bash:
    service: appserver
    cmd:
      - bash
#  node:
#    service: node
#  npm:
#    service: node
#  grunt:
#    service: node
